### PR TITLE
enabled mailing from DF 

### PR DESCRIPTION
**Pull request by philicious**
containerized DF couldnt mail yet.

This is a more general problem with Docker containers and ssmtp probably the most common fix. and simple.
for more info see https://github.com/docker-library/php/issues/135 https://github.com/docker-library/wordpress/issues/30

For configuration you add environment variables like
```
SSMTP_mailhub=mx.acme.com
SSMTP_AuthUser=df
SSMTP_AuthPass=s3cret
SSMTP_UseTLS=YES
SSMTP_UseSTARTTLS=YES
```

All configuration options from here http://manpages.ubuntu.com/manpages/trusty/man5/ssmtp.conf.5.html are working, prfixed with `SSMTP_`

good to know: 
- use `SSMTP_rewriteDomain` to make the mails seem to come from a different of your domains
- you can change the FROM via /etc/ssmtp/revaliases if you need

### CODE REVIEW

**Comment by df-arif** [comment]
@philicious , Thanks for the PR. It looks good. However, can you please update the README about this feature. You can create a new section at the bottom of the README for this. I will merge the PR once you update the README.

**Comment by philicious** [comment]
@df-arif sure. how about a matrix with all possible config options (mandatory, optional) in general? Its quite a few meanwhile but not all from .env-dist

**Comment by df-arif** [comment]
@philicious, sure. That will be even better. Thanks!

**Comment by philicious** [comment]
@df-arif will do tomorrow then. already 11pm over here

**Comment by philicious** [comment]
@df-arif have a look at https://github.com/philicious/df-docker/blob/master/README.md if thats looking ok for you

**Comment by df-arif** [comment]
@philicious , Thanks for updating the README. It looks good. PR merged.

**Pull request merged**
